### ISSUE TITLE
Missing cfinder networks file.

### ISSUE THREAD

**Issue by sari-saba-sadiya** [jintrone/TEvA#3]
Hi,

I am trying to run the example via: "java -cp TEvA.jar edu.mit.cci.teva.example.RunSampleCsv"
However, I keep getting the exception "Could not identify communities file" from the file /TEvA-master/src/edu/mit/cci/teva/cpm/cfinder/CFinderReader.java 
Examining the code, it seems that the example is looking for "/Users/jintrone/Documents/DEV/REASONTEVA/work/CFinderNetwork.TEvA.0.net_files" which ofcourse I do not have. See line 153: readCommunities(4, new File("/Users/jintrone/Documents/DEV/REASONTEVA/work/CFinderNetwork.TEvA.0.net_files"));

Where can I download "CFinderNetwork.TEvA.0.net_files" from?

**Comment by jintrone** [comment]
Hmm.  It's been a while since I looked at this, but am happy someone is trying to get this running!  You should probably use cos instead of CFinder - it's much faster.  It'll take me a day or two, but I'll push a fix and update this bug when I do.  Thanks!

**Comment by jintrone** [comment]
Ok - just checking this out now hat's just a miscellaneous bit of testing that shouldn't actually get run.  The problem, if you look at the complete stack trace, it that it can't find the clique finder algorithm, and so cannot generate the communities file.

To make this work, you need to install the "cos" fast clique percolation algorithm.  The distribution is referenced from the README.md file.   After you do that, you'll need to make sure that the properties are pointing to the correct distribution.  See "teva.default.properties" in the resources directory; you can just copy that out and then pass your copy in on the command line.

Please post another issue if you have one, and I'll be happy to try to help you out.

**Comment by sari-saba-sadiya** [comment]
Prof Introne,

Thanks for your help, I have updated the properties file to include the 'cos' in the following fashion:
cfinder_executable_path=$HOME/cosparallel-code/cos

Now it seems that I do have a 'TEvA-master/deploy/work/CFinderNetwork.TEvA.0.net' but for some reason the program is looking for "deploy/./work/CFinderNetwork.TEvA.0.net_file/k=4/communities_links".

What am I missing?

please find output below
---------------------------------------------------------------------------
06:25:40,851  INFO TextCorpusNetworkGenerator:88 - Done processing windows
06:25:40,851  INFO MemoryBasedRunner:101 - Done creating networks.
06:25:40,856  INFO EvolutionEngine:66 - Removing edges weight < 0.5 from 529
06:25:40,857  INFO EvolutionEngine:68 - 529 edges remain
06:25:40,857  INFO CFinderRunner:118 - Generating communities for CFinderNetwork.TEvA.0.net
06:25:40,928  INFO CFinderRunner:146 - Finished in 0 seconds.
06:25:40,929  WARN CFinderReader:103 - Can't identify clique file
Trying to access communities file:
/home/Projects/textFlow/TEvA-master/deploy/./work/CFinderNetwork.TEvA.0.net_files/k=4/communities_links
Now trying to access communities file:
/home/Projects/textFlow/TEvA-master/deploy/./work/CFinderNetwork.TEvA.0.net_files/k=4/intensity_communities_links
Exception in thread "main" edu.mit.cci.teva.engine.CommunityFinderException: Could not identify communities file
	at edu.mit.cci.teva.cpm.cfinder.CFinderReader.readCommunities(CFinderReader.java:47)
	at edu.mit.cci.teva.cpm.cfinder.CFinderCommunityFinder.findCommunities(CFinderCommunityFinder.java:74)
	at edu.mit.cci.teva.cpm.cfinder.CFinderCommunityFinder.findCommunities(CFinderCommunityFinder.java:100)
	at edu.mit.cci.teva.engine.EvolutionEngine.step(EvolutionEngine.java:104)
	at edu.mit.cci.teva.engine.EvolutionEngine.process(EvolutionEngine.java:73)
	at edu.mit.cci.teva.MemoryBasedRunner.process(MemoryBasedRunner.java:122)
	at edu.mit.cci.teva.MemoryBasedRunner.processAndSave(MemoryBasedRunner.java:130)
	at edu.mit.cci.teva.example.RunSampleCsv.main(RunSampleCsv.java:54)

**Comment by jintrone** [comment]
I've just pushed an update which changes the default running behavior to use COS rather than CFinder (you installed cos, but TEvA was still set to use CFinder).  Please pull down the new code. Also, make sure you've installed the maximal_cliques executable (see the readme file), and have updated the teva.default.properties (or created your own properties file) to point to the correct directories - note, that shell variables will not be expanded, so you'll need to hardcode the path in the properties file (i.e. $HOME won't work).

**Comment by sari-saba-sadiya** [comment]
Prof Introne,

Thank you for your reply. But the problem persists.

I have pulled your new code, I have downloaded and compiled both cos and the maximal_cliques, and updated 'cos_max_cliques_executable' and 'cos_executable' in teva.default.properties. I ran 'ant clean' and then 'ant', then from the deploy directory I ran 'java -cp TEvA.jar edu.mit.cci.teva.example.RunSampleCsv'.

The same problem persists, I think there is a typo somewhere in the paths as it seems to look for  'deploy/work/CFinderNetwork.TEvA.0.net_files/k=4/communities_links' while in the directory there is only 'deploy/work/CFinderNetwork.TEvA.0.net'.

Please see output below:

06:01:04,389  INFO TextCorpusNetworkGenerator:82 - Will process 19 windows
06:01:04,389  INFO TextCorpusNetworkGenerator:84 - Process window 0
06:01:06,333  INFO TextCorpusNetworkGenerator:84 - Process window 1
06:01:07,132  INFO TextCorpusNetworkGenerator:84 - Process window 2
06:01:07,863  INFO TextCorpusNetworkGenerator:84 - Process window 3
06:01:08,544  INFO TextCorpusNetworkGenerator:84 - Process window 4
06:01:09,245  INFO TextCorpusNetworkGenerator:84 - Process window 5
06:01:09,969  INFO TextCorpusNetworkGenerator:84 - Process window 6
06:01:10,665  INFO TextCorpusNetworkGenerator:84 - Process window 7
06:01:11,345  INFO TextCorpusNetworkGenerator:84 - Process window 8
06:01:11,980  INFO TextCorpusNetworkGenerator:84 - Process window 9
06:01:12,604  INFO TextCorpusNetworkGenerator:84 - Process window 10
06:01:13,205  INFO TextCorpusNetworkGenerator:84 - Process window 11
06:01:13,710  INFO TextCorpusNetworkGenerator:84 - Process window 12
06:01:14,236  INFO TextCorpusNetworkGenerator:84 - Process window 13
06:01:14,867  INFO TextCorpusNetworkGenerator:84 - Process window 14
06:01:15,508  INFO TextCorpusNetworkGenerator:84 - Process window 15
06:01:16,116  INFO TextCorpusNetworkGenerator:84 - Process window 16
06:01:16,850  INFO TextCorpusNetworkGenerator:84 - Process window 17
06:01:17,589  INFO TextCorpusNetworkGenerator:84 - Process window 18
06:01:18,294  INFO TextCorpusNetworkGenerator:88 - Done processing windows
06:01:18,295  INFO MemoryBasedRunner:101 - Done creating networks.
06:01:18,300  INFO EvolutionEngine:66 - Removing edges weight < 0.5 from 529
06:01:18,301  INFO EvolutionEngine:68 - 529 edges remain
06:01:18,301  INFO CFinderRunner:118 - Generating communities for CFinderNetwork.TEvA.0.net
06:01:18,394  INFO CFinderRunner:146 - Finished in 0 seconds.
06:01:18,402  WARN CFinderReader:103 - Can't identify clique file
Trying to access communities file:
/home/sarisadiya/Projects/textFlow/old/TEvA-master/deploy/./work/CFinderNetwork.TEvA.0.net_files/k=4/communities_links
Now trying to access communities file:
/home/sarisadiya/Projects/textFlow/old/TEvA-master/deploy/./work/CFinderNetwork.TEvA.0.net_files/k=4/intensity_communities_links
Exception in thread "main" edu.mit.cci.teva.engine.CommunityFinderException: Could not identify communities file
	at edu.mit.cci.teva.cpm.cfinder.CFinderReader.readCommunities(CFinderReader.java:47)
	at edu.mit.cci.teva.cpm.cfinder.CFinderCommunityFinder.findCommunities(CFinderCommunityFinder.java:74)
	at edu.mit.cci.teva.cpm.cfinder.CFinderCommunityFinder.findCommunities(CFinderCommunityFinder.java:100)
	at edu.mit.cci.teva.engine.EvolutionEngine.step(EvolutionEngine.java:104)
	at edu.mit.cci.teva.engine.EvolutionEngine.process(EvolutionEngine.java:73)
	at edu.mit.cci.teva.MemoryBasedRunner.process(MemoryBasedRunner.java:122)
	at edu.mit.cci.teva.MemoryBasedRunner.processAndSave(MemoryBasedRunner.java:130)
	at edu.mit.cci.teva.example.RunSampleCsv.main(RunSampleCsv.java:54)

**Comment by jintrone** [comment]
There is no typo.  You are still running the CFinder community finder, and the recent commit changed the default behavior to use the CosCommunityFinder; for whatever reason, this commit has not been applied in your executable code.  Please verify that lines 136 - 138 in TEvA/src/edu/mit/cci/teva/DefaultTevaFactory.java appear correctly in your local copy.  They should look like:

```java    
public CommunityFinder getFinder() {
        return new CosCommunityFinder(params);
}
```

If they do, than clean and rebuild before trying to run again.
